name: Waka Readme

on:
  schedule:
    # Runs at 0:00 CST
    - cron: '00 16 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
          IGNORED_REPOS: "flyme6-device-bacon, flyme6-device-h830, flyme6-device-oneplus3, Lenovo_G40_70M_EFI, Shinelon_YAO_7000"
